# Generated by Django 3.2.18 on 2023-03-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_post_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
