# Generated by Django 3.2.18 on 2023-03-07 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0009_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='author',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='object_id',
        ),
        migrations.AddField(
            model_name='gallery',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='contenttypes.contenttype'),
        ),
    ]
